
TARGET=cairo

TEMPLATE=lib
CONFIG+=staticlib
INCLUDEPATH = $${PWD}/CAMotics/src/cairo
DEFINES = HAVE_STDINT_H HAVE_PTHREAD_H CAIRO_NO_MUTEX HAVE_INTTYPES_H CAIRO_HAS_IMAGE_SURFACE
OBJECTS_DIR=lib$${TARGET}

SOURCES += $${PWD}/CAMotics/src/cairo/cairo-image-surface.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-font-options.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-cache.c
SOURCES += $${PWD}/CAMotics/src/cairo/pixman-solid-fill.c
SOURCES += $${PWD}/CAMotics/src/cairo/pixman-radial-gradient.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-font-face-twin.c
SOURCES += $${PWD}/CAMotics/src/cairo/pixman-fast-path.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-atomic.c
SOURCES += $${PWD}/CAMotics/src/cairo/pixman-cpu.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-path-bounds.c
SOURCES += $${PWD}/CAMotics/src/cairo/pixman-image.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-scaled-font.c
SOURCES += $${PWD}/CAMotics/src/cairo/pixman-combine64.c
SOURCES += $${PWD}/CAMotics/src/cairo/pixman-edge-accessors.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-region.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-unicode.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-color.c
SOURCES += $${PWD}/CAMotics/src/cairo/pixman-gradient-walker.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-clip.c
SOURCES += $${PWD}/CAMotics/src/cairo/pixman-region32.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-skiplist.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-hash.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-analysis-surface.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-slope.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-path-fill.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-font-face.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-freelist.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-wideint.c
SOURCES += $${PWD}/CAMotics/src/cairo/pixman-matrix.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-matrix.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-surface.c
SOURCES += $${PWD}/CAMotics/src/cairo/pixman-region16.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-traps.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-pen.c
SOURCES += $${PWD}/CAMotics/src/cairo/pixman-implementation.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-path-fixed.c
SOURCES += $${PWD}/CAMotics/src/cairo/pixman-general.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-arc.c
SOURCES += $${PWD}/CAMotics/src/cairo/pixman-combine32.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-path.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-version.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-surface-fallback.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-gstate.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-polygon.c
SOURCES += $${PWD}/CAMotics/src/cairo/pixman-bits-image.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-hull.c
SOURCES += $${PWD}/CAMotics/src/cairo/pixman-access-accessors.c
SOURCES += $${PWD}/CAMotics/src/cairo/pixman-access.c
SOURCES += $${PWD}/CAMotics/src/cairo/pixman.c
SOURCES += $${PWD}/CAMotics/src/cairo/pixman-linear-gradient.c
SOURCES += $${PWD}/CAMotics/src/cairo/pixman-utils.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-pattern.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-stroke-style.c
SOURCES += $${PWD}/CAMotics/src/cairo/pixman-trap.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-user-font.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-spline.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-bentley-ottmann.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-meta-surface.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-misc.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-path-stroke.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-rectangle.c
SOURCES += $${PWD}/CAMotics/src/cairo/pixman-edge.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-array.c
SOURCES += $${PWD}/CAMotics/src/cairo/cairo-font-face-twin-data.c
