#ifndef _PAL_CONFIG_H_INCLUDED
#define _PAL_CONFIG_H_INCLUDED 1

#define HAVE_IEEEFP_H 0
#define HAVE_ALLOCA_H 1
#define HAVE_SYS_VMPARAM_H 1
#define HAVE_MACH_VM_TYPES_H 1
#define HAVE_MACH_VM_PARAM_H 1
#define HAVE_PROCFS_H 0
#define HAVE_CRT_EXTERNS_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_PTHREAD_NP_H 0
#define HAVE_SYS_LWP_H 0
#define HAVE_RUNETYPE_H 1

#define HAVE_KQUEUE 1
#define HAVE_GETPWUID_R 1
#define HAVE_PTHREAD_SUSPEND 0
#define HAVE_PTHREAD_SUSPEND_NP 0
#define HAVE_PTHREAD_CONTINUE 0
#define HAVE_PTHREAD_RESUME_NP 0
#define HAVE_PTHREAD_CONTINUE_NP 0
#define HAVE_PTHREAD_ATTR_GET_NP 0
#define HAVE_PTHREAD_GETATTR_NP 0
#define HAVE_PTHREAD_SIGQUEUE 0
#define HAVE_SIGRETURN 0
#define HAVE__THREAD_SYS_SIGRETURN 0
#define HAVE_COPYSIGN 1
#define HAVE_FSYNC 1
#define HAVE_FUTIMES 1
#define HAVE_UTIMES 1
#define HAVE_SYSCTL 1
#define HAVE_SYSCONF 1
#define HAVE_LOCALTIME_R 1
#define HAVE_GMTIME_R 1
#define HAVE_TIMEGM 1
#define HAVE__SNWPRINTF 0
#define HAVE_POLL 1
#define HAVE_STATVFS 1
#define HAVE_THREAD_SELF 0
#define HAVE__LWP_SELF 0
#define HAVE_MACH_THREADS 1
#define HAVE_MACH_EXCEPTIONS 1
#define HAVE_VM_ALLOCATE 1
#define HAVE_VM_READ 1
#define HAS_SYSV_SEMAPHORES 1
#define HAS_PTHREAD_MUTEXES 1
#define HAVE_TTRACE 0

#define HAVE_STAT_TIMESPEC 1
#define HAVE_STAT_NSEC 0
#define HAVE_TM_GMTOFF 1

#define HAVE_BSD_REGS_T 0
#define HAVE_PT_REGS 0
#define HAVE_GREGSET_T 0
#define HAVE_SIGINFO_T 1
#define HAVE_UCONTEXT_T 0
#define HAVE_PTHREAD_RWLOCK_T 1
#define HAVE_PRWATCH_T 0
#define SIZEOF_OFF_T 8

#define HAVE_YIELD_SYSCALL 0
#define HAVE_INFTIM 0
#define HAVE_CHAR_BIT 0
#define USER_H_DEFINES_DEBUG 0
#define HAVE__SC_PHYS_PAGES 1
#define HAVE__SC_AVPHYS_PAGES 0

#define REALPATH_SUPPORTS_NONEXISTENT_FILES 0
#define SSCANF_CANNOT_HANDLE_MISSING_EXPONENT 0
#define SSCANF_SUPPORT_ll 1
#define HAVE_LARGE_SNPRINTF_SUPPORT 1
#define HAVE_BROKEN_FIFO_SELECT 0
#define HAVE_BROKEN_FIFO_KEVENT 0
#define HAS_FTRUNCATE_LENGTH_ISSUE 1
#define HAVE_SCHED_GET_PRIORITY 1
#define HAVE_SCHED_GETCPU 0
#define HAVE_WORKING_GETTIMEOFDAY 1
#define HAVE_WORKING_CLOCK_GETTIME 0
#define HAVE_CLOCK_MONOTONIC 0
#define HAVE_CLOCK_MONOTONIC_COARSE 0
#define HAVE_MACH_ABSOLUTE_TIME 1
#define HAVE_CLOCK_THREAD_CPUTIME 0
#define STATVFS64_PROTOTYPE_BROKEN 0
#define HAVE_MMAP_DEV_ZERO 0
#define MMAP_IGNORES_HINT 0
#define MMAP_ANON_IGNORES_PROTECTION 0
#define MMAP_DOESNOT_ALLOW_REMAP 0
#define ONE_SHARED_MAPPING_PER_FILEREGION_PER_PROCESS 0
#define PTHREAD_CREATE_MODIFIES_ERRNO 0
#define SEM_INIT_MODIFIES_ERRNO 0
#define HAVE_PROCFS_CTL 0
#define HAVE_COMPATIBLE_ACOS 1
#define HAVE_COMPATIBLE_ASIN 1
#define HAVE_COMPATIBLE_ATAN2 1
#define HAVE_COMPATIBLE_EXP 0
#define HAVE_COMPATIBLE_LOG 1
#define HAVE_COMPATIBLE_LOG10 1
#define UNGETC_NOT_RETURN_EOF 0
#define HAS_POSIX_SEMAPHORES 0
#define GETPWUID_R_SETS_ERRNO 0
#define FILE_OPS_CHECK_FERROR_OF_PREVIOUS_CALL 0

#define PAL_THREAD_PRIORITY_MIN 0
#define PAL_THREAD_PRIORITY_MAX 0

#define HAVE_COREFOUNDATION 1
#define HAVE__NSGETENVIRON 1
#define DEADLOCK_WHEN_THREAD_IS_SUSPENDED_WHILE_BLOCKED_ON_MUTEX 1
#define PAL_PTRACE(cmd, pid, addr, data) ptrace((cmd), (pid), (caddr_t)(addr), (data))
#define PAL_PT_ATTACH PT_ATTACH
#define PAL_PT_DETACH PT_DETACH
#define PAL_PT_READ_D PT_READ_D
#define PAL_PT_WRITE_D PT_WRITE_D
#define SYNCHMGR_SUSPENSION_SAFE_CONDITION_SIGNALING 1
#define ERROR_FUNC_FOR_GLOB_HAS_FIXED_PARAMS 1
#define HAS_FTRUNCATE_LENGTH_ISSUE 1
/* #undef FREEBSD_LIBC */

#define JA_JP_LOCALE_NAME "ja_JP.SJIS"
#define KO_KR_LOCALE_NAME "ko_KR.eucKR"
#define ZH_TW_LOCALE_NAME "zh_TG.BIG5"

#define CHECK_TRACE_SPECIFIERS 0
#define PROCFS_MEM_NAME ""
#define HAVE_GETHRTIME 0
#define HAVE_LOWERCASE_ISO_NAME 0
#define HAVE_READ_REAL_TIME 0
#define HAVE_UNDERSCORE_ISO_NAME 0
#define MKSTEMP64_IS_USED_INSTEAD_OF_MKSTEMP 0
#define NEED_DLCOMPAT 0
#define OPEN64_IS_USED_INSTEAD_OF_OPEN 0
#define SELF_SUSPEND_FAILS_WITH_NATIVE_SUSPENSION 0
#define SET_SCHEDPARAM_NEEDS_PRIVS 0
#define SIGWAIT_FAILS_WHEN_PASSED_FULL_SIGSET 0
#define SYNCHMGR_PIPE_BASED_THREAD_BLOCKING 0
#define WRITE_0_BYTES_HANGS_TTY 0
#define HAVE_FTRUNCATE_LARGE_LENGTH_SUPPORT 1
#endif
